image: ubuntu:18.04

stages:
  - style
  - quality
  - build

before_script:
  - apt-get update
  - apt-get upgrade
  - apt-get install python3-pip -y

style:
  stage: style
  script:
  - pip3 install pep8
  - cd tests
  - python3 style.py

quality:
  stage: quality
  script:
  - pip3 install pep8 pylint
  - cd tests
  - python3 quality.py

build:
  stage: build
  script:
  - pip3 install pyinstaller
  - pyinstaller -F ./src/main.py
  - ls
  artifacts:
    paths:
    - dist
  only:
  - master
  - dev
