image: ubuntu:18.04

stages:
  - style
  - quality
  - build

before_script:
  - apt update
  - apt upgrade
  - apt install python3-pip -y
  - pip3 install pep8 pylint

style:
  stage: style
  script:
  - cd tests
  - python3 style.py

quality:
  stage: quality
  script:
  - pip3 install pylint
  - cd tests
  - python3 quality.py

build:
    stage: build
    script:
    - pip install cx_freeze
    - python3 setup.py build
